POST http://localhost:8080/events/1/register
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwiZXhwIjoxNzQ0NTMzMzExLCJ1c2VySWQiOjF9.2QYgomFS2xWe1V3dsU5NiYXPJZWJ5xUKxrWGlp63mek
